#!/usr/bin/env bun
/**
 * Regenerate the tmux-dependency inventory artifacts from `audit.config.json`.
 *
 *   bun src/cli/tmux-audit/generate.ts
 *
 * Writes `inventory.json` (machine-readable) and `inventory.md` (summary).
 * Exits non-zero if any scanned production file is unclassified — fix the
 * manifest (add an override or rule) and re-run. Never mutates production code.
 */

import { writeFileSync } from "node:fs";
import path from "node:path";
import {
	buildInventory,
	loadConfig,
	resolveRepoRoot,
	type AuditConfig,
	type Inventory,
	type InventoryEntry,
} from "./inventory";

function renderTable(rows: string[][], headers: string[]): string {
	const head = `| ${headers.join(" | ")} |`;
	const sep = `| ${headers.map(() => "---").join(" | ")} |`;
	const body = rows.map((r) => `| ${r.join(" | ")} |`).join("\n");
	return `${head}\n${sep}\n${body}`;
}

function countTable(record: Record<string, number>, keyHeader: string, describe?: Record<string, string>): string {
	const rows = Object.entries(record).map(([key, count]) => {
		const cells = [`\`${key}\``, String(count)];
		if (describe) cells.push(describe[key] ?? "");
		return cells;
	});
	const headers = describe ? [keyHeader, "Count", "Meaning"] : [keyHeader, "Count"];
	return renderTable(rows, headers);
}

function renderMarkdown(inv: Inventory, config: AuditConfig): string {
	const deepInternal = inv.byDepth["deep-internal"] ?? 0;
	const callers = inv.byDepth["caller"] ?? 0;
	const active = inv.byDependencyKind["active"] ?? 0;
	const reference = inv.byDependencyKind["reference"] ?? 0;

	const sections: string[] = [];
	sections.push(
		"# Remaining tmux dependency inventory",
		"",
		"> Generated by `bun src/cli/tmux-audit/generate.ts` from `audit.config.json`.",
		"> Do not edit by hand — edit the manifest and regenerate. Roadmap item: **INT-008** (Seq 1251).",
		"",
		"This is the deletion map later tmux-removal tasks consume. Each row names the owning file,",
		"its current consumer, the roadmap item that retires it, and what must be true before it can go.",
		"",
		"## Scan boundary",
		"",
		config.boundary.note,
		"",
		`- **Excluded dirs:** ${config.boundary.excludeDirs.map((d) => `\`${d}\``).join(", ")}`,
		`- **Excluded extensions:** ${config.boundary.excludeExtensions.map((e) => `\`${e}\``).join(" ")}`,
		`- **Historical (counted, not inventoried):** ${config.boundary.historicalDirs.map((d) => `\`${d}\``).join(", ")} — ${config.boundary.historicalNote}`,
		"",
		"## Baseline counts",
		"",
		`- Tracked files scanned: **${inv.totals.trackedFiles}**`,
		`- In-boundary files with **no** tmux signal: **${inv.totals.inBoundaryClean}**`,
		`- **Inventoried tmux dependencies: ${inv.totals.inventoried}** (${inv.totals.occurrences} signal occurrences)`,
		`- Historical references (changelogs + ADRs, out of scope): **${inv.historical.fileCount}** files, ${inv.historical.occurrences} occurrences`,
		`- Deep \`TmuxClient\` internals: **${deepInternal}** · callers that still know tmux vocabulary: **${callers}**`,
		`- Active dependencies (behavior changes on removal): **${active}** · reference-only mentions: **${reference}**`,
		"",
		"### By category",
		"",
		countTable(inv.byCategory, "Category", config.categories),
		"",
		"### By depth",
		"",
		countTable(inv.byDepth, "Depth", config.depths),
		"",
		"### By dependency kind",
		"",
		countTable(inv.byDependencyKind, "Kind", config.dependencyKinds),
		"",
		"### By target roadmap item",
		"",
		countTable(inv.byRoadmapItem, "Roadmap item", config.roadmap),
		"",
		"## Inventory",
		"",
	);

	// One table per category, entries sorted by depth then path.
	const depthRank: Record<string, number> = { "deep-internal": 0, caller: 1, surface: 2, isolation: 3, test: 4 };
	const byCategory = new Map<string, InventoryEntry[]>();
	for (const e of inv.entries) {
		const list = byCategory.get(e.category) ?? [];
		list.push(e);
		byCategory.set(e.category, list);
	}
	for (const category of Object.keys(inv.byCategory)) {
		const list = (byCategory.get(category) ?? []).sort(
			(a, b) => (depthRank[a.depth] ?? 9) - (depthRank[b.depth] ?? 9) || a.path.localeCompare(b.path),
		);
		sections.push(`### ${category} — ${config.categories[category] ?? ""}`, "");
		const rows = list.map((e) => [
			`\`${e.path}\``,
			e.depth,
			e.dependencyKind,
			`\`${e.roadmapItem}\``,
			e.consumer,
			e.deletionPrerequisite,
		]);
		sections.push(renderTable(rows, ["File", "Depth", "Kind", "Roadmap", "Consumer", "Deletion prerequisite"]), "");
	}

	return sections.join("\n") + "\n";
}

function main(): void {
	const repoRoot = resolveRepoRoot();
	const config = loadConfig(repoRoot);
	const inv = buildInventory(repoRoot, config);

	if (inv.unclassified.length > 0) {
		console.error(`\n${inv.unclassified.length} unclassified tmux dependency file(s) — add an override or rule:\n`);
		for (const f of inv.unclassified) {
			console.error(`  ${f.path}  (occ ${f.occurrences}; tokens: ${Object.keys(f.tokens).sort().join(", ")})`);
		}
		process.exit(1);
	}

	const jsonPath = path.join(repoRoot, "src/cli/tmux-audit/inventory.json");
	const mdPath = path.join(repoRoot, "src/cli/tmux-audit/inventory.md");

	const json = {
		$generatedBy: "bun src/cli/tmux-audit/generate.ts",
		$doNotEdit: "Regenerate from audit.config.json instead.",
		roadmapItem: "INT-008",
		boundary: {
			note: config.boundary.note,
			excludeDirs: config.boundary.excludeDirs,
			historicalDirs: config.boundary.historicalDirs,
			historicalNote: config.boundary.historicalNote,
			excludeExtensions: config.boundary.excludeExtensions,
			excludePaths: config.boundary.excludePaths,
		},
		totals: inv.totals,
		historical: inv.historical,
		hiddenGrammarFiles: inv.hiddenGrammarFiles,
		byCategory: inv.byCategory,
		byDepth: inv.byDepth,
		byDependencyKind: inv.byDependencyKind,
		byRoadmapItem: inv.byRoadmapItem,
		entries: inv.entries,
	};

	writeFileSync(jsonPath, JSON.stringify(json, null, "\t") + "\n");
	writeFileSync(mdPath, renderMarkdown(inv, config));
	console.log(`Wrote inventory: ${inv.totals.inventoried} dependencies across ${Object.keys(inv.byCategory).length} categories.`);
	console.log(`  ${jsonPath}`);
	console.log(`  ${mdPath}`);
}

main();
