/**
 * The omp status extension: a TypeScript module omp loads with `--hook`, which
 * reports the session's lifecycle to the board through `dev3 hook omp`.
 *
 * omp has no Claude/Codex-style JSON hooks. Its extension API runs in-process
 * and hands every event to a handler, so the module below is the whole bridge:
 * it maps omp's events onto the status-hook vocabulary Codex already speaks
 * (`STATUS_HOOK_EVENTS`) and spawns one dev3 CLI process per report, exactly
 * like a Codex hook command. The body is generated here (pure) and written by
 * `writeOmpStatusExtension` (I/O), mirroring the build/write split of the
 * Claude and Codex hooks.
 *
 * The file lives under the dev3 home rather than in each worktree, for the same
 * reason the Codex declarations live in `~/.codex/config.toml`: it is one
 * generated artifact, rewritten before every launch, referenced by absolute path.
 */

import { existsSync, mkdirSync, readFileSync, renameSync, rmSync, writeFileSync } from "node:fs";
import { resolveDev3Home } from "./dev3-home";
import { type Dev3CliLookup, resolveDev3CliPath } from "./dev3-cli-path";

export const OMP_STATUS_EXTENSION_BASENAME = "omp-status.ts";
export const OMP_HOOK_SUBCOMMAND = "hook omp";

/** Where the extension is written: `<dev3 home>/data/agent-hooks/omp-status.ts`. */
export function ompStatusExtensionPath(dev3Home: string = resolveDev3Home()): string {
	return `${dev3Home}/data/agent-hooks/${OMP_STATUS_EXTENSION_BASENAME}`;
}

/**
 * The dev3 CLI as the extension spawns it: an absolute path, because the
 * module runs inside omp's own process with no shell to expand `~`. POSIX gets
 * `<dev3 home>/bin/dev3`, where the app installs the binary; Windows the same
 * lookup the generated hook commands use.
 */
export function ompStatusHookCli(lookup: Dev3CliLookup = {}): string {
	const platform = lookup.platform ?? process.platform;
	if (platform === "win32") return resolveDev3CliPath({ ...lookup, platform });
	return `${resolveDev3Home()}/bin/dev3`;
}

/**
 * The extension module, with the CLI path baked in.
 *
 * Event mapping, into the Codex vocabulary the socket handler expects:
 *
 * | omp event                 | reported as        |
 * |---------------------------|--------------------|
 * | `session_start`           | `SessionStart`     |
 * | `input` (human text)      | `UserPromptSubmit` + prompt |
 * | `agent_start`             | `UserPromptSubmit` |
 * | `tool_execution_start`    | `PreToolUse`       |
 * | `tool_execution_end`      | `PostToolUse`      |
 * | `tool_approval_requested` | `PermissionRequest`|
 * | `tool_approval_resolved`  | `PostToolUse`      |
 * | `agent_end`               | `Stop`             |
 *
 * Two behaviours are deliberate. Reports are queued one after another, because
 * two concurrent dev3 processes could land a tool's "done" after the agent's
 * "stopped" and strand the task in-progress. And while the agent is already
 * known to be working, tool events are re-sent only every `WORKING_REFRESH_MS`,
 * so a long tool-heavy turn costs a handful of processes instead of hundreds —
 * the refresh keeps a card the user dragged elsewhere from staying wrong for
 * the whole turn.
 */
export function buildOmpStatusExtension(options?: { cli?: string }): string {
	const cli = JSON.stringify(options?.cli ?? ompStatusHookCli());
	return `// Generated by dev3 — do not edit. Rewritten before every omp launch.
// Reports this omp session's lifecycle to the dev3 board through \`dev3 ${OMP_HOOK_SUBCOMMAND}\`
// so the task follows the agent between columns without manual \`dev3 task move\` calls.
import { spawn } from "node:child_process";
import { randomUUID } from "node:crypto";

const DEV3_CLI = ${cli};
const HOOK_ARGS = ["hook", "omp"];
const WORKING_REFRESH_MS = 10_000;
const HOOK_TIMEOUT_MS = 8_000;

type Ctx = { cwd?: string; sessionManager?: { getSessionId?: () => string } };
type Payload = { event: string; sessionId?: string; prompt?: string; submissionId?: string };

export default function dev3StatusHooks(pi: any): void {
	// Only a pane dev3 launched carries DEV3_TASK_ID; anywhere else this module is inert.
	if (!process.env.DEV3_TASK_ID) return;

	let queue: Promise<void> = Promise.resolve();
	let working = false;
	let lastWorkingAt = 0;

	const warn = (text: string): void => {
		try {
			pi.logger?.warn?.(\`dev3 status hook: \${text}\`);
		} catch {}
	};

	const sessionIdOf = (ctx: Ctx | undefined): string | undefined => {
		try {
			const id = ctx?.sessionManager?.getSessionId?.();
			return typeof id === "string" && id ? id : undefined;
		} catch {
			return undefined;
		}
	};

	const deliver = (payload: Payload, cwd: string): Promise<void> =>
		new Promise((resolve) => {
			let child: ReturnType<typeof spawn>;
			try {
				child = spawn(DEV3_CLI, HOOK_ARGS, { cwd, stdio: ["pipe", "ignore", "pipe"], windowsHide: true });
			} catch (err) {
				warn(String(err));
				resolve();
				return;
			}
			let stderr = "";
			const timer = setTimeout(() => {
				try { child.kill(); } catch {}
			}, HOOK_TIMEOUT_MS);
			child.stderr?.on("data", (chunk) => { stderr += String(chunk); });
			child.on("error", (err) => warn(String(err)));
			child.on("close", () => {
				clearTimeout(timer);
				if (stderr.trim()) warn(stderr.trim());
				resolve();
			});
			child.stdin?.on("error", () => {});
			child.stdin?.end(JSON.stringify(payload));
		});

	const report = (ctx: Ctx | undefined, event: string, extra?: Partial<Payload>): void => {
		const sessionId = sessionIdOf(ctx);
		const payload: Payload = { event, ...(sessionId ? { sessionId } : {}), ...extra };
		const cwd = typeof ctx?.cwd === "string" && ctx.cwd ? ctx.cwd : process.cwd();
		// Strictly in event order, one dev3 process at a time (see the header).
		queue = queue.then(() => deliver(payload, cwd));
	};

	const reportWorking = (ctx: Ctx | undefined, event: string, extra?: Partial<Payload>): void => {
		const now = Date.now();
		if (working && !extra && now - lastWorkingAt < WORKING_REFRESH_MS) return;
		working = true;
		lastWorkingAt = now;
		report(ctx, event, extra);
	};

	const reportIdle = (ctx: Ctx | undefined, event: string): void => {
		working = false;
		report(ctx, event);
	};

	// A session belongs to the agent whose runner loaded this module; an approval
	// raised for another session in the same process is not this task's.
	const ownSession = (event: { sessionId?: string } | undefined, ctx: Ctx | undefined): boolean => {
		const own = sessionIdOf(ctx);
		return !event?.sessionId || !own || event.sessionId === own;
	};

	pi.on("session_start", (_event: unknown, ctx: Ctx) => {
		working = false;
		report(ctx, "SessionStart");
	});
	// The submitted text rides on the status report so the human's prompt reaches
	// Agent traffic; an extension-sourced input is the harness talking to itself.
	pi.on("input", (event: { text?: string; source?: string }, ctx: Ctx) => {
		const human = event?.source !== "extension" && typeof event?.text === "string" && event.text.trim();
		reportWorking(ctx, "UserPromptSubmit", human ? { prompt: event.text, submissionId: randomUUID() } : undefined);
	});
	pi.on("agent_start", (_event: unknown, ctx: Ctx) => reportWorking(ctx, "UserPromptSubmit"));
	pi.on("tool_execution_start", (_event: unknown, ctx: Ctx) => reportWorking(ctx, "PreToolUse"));
	pi.on("tool_execution_end", (_event: unknown, ctx: Ctx) => reportWorking(ctx, "PostToolUse"));
	pi.on("tool_approval_requested", (event: { sessionId?: string }, ctx: Ctx) => {
		if (ownSession(event, ctx)) reportIdle(ctx, "PermissionRequest");
	});
	pi.on("tool_approval_resolved", (event: { sessionId?: string }, ctx: Ctx) => {
		if (ownSession(event, ctx)) reportWorking(ctx, "PostToolUse");
	});
	// An agent_end that omp will follow with its own retry is not a settle.
	pi.on("agent_end", (event: { willContinue?: boolean }, ctx: Ctx) => {
		if (event?.willContinue) return;
		reportIdle(ctx, "Stop");
	});
}
`;
}

/**
 * Write the extension for this machine and return its path. Skipped when the
 * file already holds the same body; otherwise written through a temp name in
 * the same directory, because the reader is another process — an omp that is
 * starting must see the old module or the new one, never a half-written file.
 *
 * Throws when it cannot be written: a launch without the flag is the honest
 * outcome, and the caller logs it.
 */
export function writeOmpStatusExtension(options?: { dev3Home?: string; cli?: string }): string {
	const path = ompStatusExtensionPath(options?.dev3Home);
	const body = buildOmpStatusExtension({ cli: options?.cli });
	const dir = path.slice(0, path.lastIndexOf("/"));
	mkdirSync(dir, { recursive: true });
	if (existsSync(path) && readFileSync(path, "utf-8") === body) return path;
	const temp = `${path}.${process.pid}.tmp`;
	try {
		writeFileSync(temp, body, "utf-8");
		renameSync(temp, path);
	} catch (err) {
		rmSync(temp, { force: true });
		throw err;
	}
	return path;
}
