/**
 * Builds the public /changelog/ page of the landing site from real data only:
 * published GitHub Releases (tag + date) and the change-logs/ entries each
 * release's tag tree contains. scripts/generate-site-changelog.ts does the I/O.
 */
import type { ChangelogEntry } from "./types";
import { buildReleaseNotesSections, type ReleaseNotesSection } from "./update-changelog";

export interface PublishedRelease {
	tag: string;
	publishedAt: string; // ISO timestamp from the GitHub Release
}

export interface SiteChangelogRelease extends PublishedRelease {
	sections: ReleaseNotesSection[];
}

/** An entry's identity across date moves: the file name, without its YYYY/MM/DD directory. */
/** The entry's whole first sentence; `title` is cut at ~120 characters for the in-app popover. */
export function fullEntryTitle(entry: Pick<ChangelogEntry, "title" | "body">): string {
	if (!entry.body || !entry.title.endsWith("...")) return entry.title;
	return entry.body.split(/\.(?:\s|$)/)[0]?.trim() || entry.title;
}

export function entryFileName(entry: Pick<ChangelogEntry, "type" | "slug">): string {
	return `${entry.type}-${entry.slug}.md`;
}

/**
 * Attribute every current changelog entry to the first published release whose
 * tag tree contained its file. Entries no release has shipped yet are left out.
 * Returns releases newest first.
 */
export function assignEntriesToReleases(
	releases: PublishedRelease[],
	fileNamesByTag: Map<string, string[]>,
	entries: ChangelogEntry[],
): SiteChangelogRelease[] {
	const firstRelease = new Map<string, string>();
	const oldestFirst = [...releases].sort((a, b) => a.publishedAt.localeCompare(b.publishedAt));
	for (const release of oldestFirst) {
		for (const name of fileNamesByTag.get(release.tag) ?? []) {
			if (!firstRelease.has(name)) firstRelease.set(name, release.tag);
		}
	}

	const byTag = new Map<string, ChangelogEntry[]>();
	for (const entry of entries) {
		const tag = firstRelease.get(entryFileName(entry));
		if (!tag) continue;
		const list = byTag.get(tag) ?? [];
		list.push({ ...entry, title: fullEntryTitle(entry) });
		byTag.set(tag, list);
	}

	return oldestFirst
		.reverse()
		.map((release) => ({ ...release, sections: buildReleaseNotesSections(byTag.get(release.tag) ?? []) }));
}

const escapeHtml = (s: string) =>
	s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/** Escapes, then renders the one bit of Markdown changelog titles use: `inline code`. */
const renderTitle = (s: string) => escapeHtml(s).replace(/`([^`]+)`/g, "<code>$1</code>");

function renderRelease(release: SiteChangelogRelease, repoUrl: string): string {
	const tag = escapeHtml(release.tag);
	const day = release.publishedAt.slice(0, 10);
	const body =
		release.sections.length === 0
			? `<p class="muted">Notes for this release are on its GitHub Release page.</p>`
			: release.sections
					.map(
						(s) =>
							`<h3>${escapeHtml(s.heading)}</h3>\n<ul>\n${s.titles.map((t) => `<li>${renderTitle(t)}</li>`).join("\n")}\n</ul>`,
					)
					.join("\n");
	return `<section class="release" id="${tag}">
<div class="release-head"><h2>${tag}</h2><time datetime="${day}">${day}</time><a class="release-link" href="${repoUrl}/releases/tag/${encodeURIComponent(release.tag)}">GitHub Release</a></div>
${body}
</section>`;
}

export function renderSiteChangelogPage(releases: SiteChangelogRelease[], repoUrl: string): string {
	return `<!DOCTYPE html>
<!-- Generated by scripts/generate-site-changelog.ts at deploy time — do not edit. -->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Changelog — dev-3.0</title>
<meta name="description" content="What changed in every dev-3.0 (dev3) release, with release dates and links to each GitHub Release.">
<link rel="canonical" href="https://dev3.h0x91b.com/changelog/">
<meta property="og:title" content="Changelog — dev-3.0">
<meta property="og:description" content="What changed in every dev-3.0 release.">
<meta property="og:type" content="website">
<meta property="og:site_name" content="dev-3.0">
<meta property="og:url" content="https://dev3.h0x91b.com/changelog/">
<meta property="og:image" content="https://dev3.h0x91b.com/og-image.jpg">
<meta name="theme-color" content="#060915">
<link rel="icon" type="image/png" href="/icon-192.png">
<link rel="stylesheet" href="/site.css">
</head>
<body>
<header class="site-header">
  <div class="site-header-inner">
    <a class="site-logo" href="/"><img src="/icon-192.png" width="30" height="30" alt=""> dev-3.0</a>
    <nav aria-label="Site">
      <ul class="site-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/docs/">Docs</a></li>
        <li><a href="/changelog/" aria-current="page">Changelog</a></li>
        <li><a href="/integrations/">Integrations</a></li>
        <li><a href="/pricing/">Pricing</a></li>
        <li><a href="${repoUrl}">GitHub</a></li>
      </ul>
    </nav>
  </div>
</header>

<main>
  <p class="eyebrow">Changelog</p>
  <h1>What changed in each release</h1>
  <p class="lede">Features, fixes and refactors in every published dev-3.0 release, newest first. Dates are when the GitHub Release was published. Download links and platform notes are on each GitHub Release.</p>
${releases.map((r) => renderRelease(r, repoUrl)).join("\n")}
</main>

<footer class="site-footer">
  <div class="site-footer-inner">
    <span>dev-3.0 (dev3) — free and open source, Apache 2.0</span>
    <ul>
      <li><a href="${repoUrl}/releases">Releases</a></li>
      <li><a href="${repoUrl}/issues">Issues</a></li>
      <li><a href="/llms.txt">llms.txt</a></li>
    </ul>
  </div>
</footer>
</body>
</html>
`;
}
