// Generated by ios/scripts/gen-theme.ts from the desktop design sources. Do not edit.
// swiftlint:disable file_length

import SwiftUI

public struct Dev3RGBA: Equatable, Sendable {
    public let red: UInt8
    public let green: UInt8
    public let blue: UInt8
    public let opacity: Double

    public init(red: UInt8, green: UInt8, blue: UInt8, opacity: Double = 1) {
        self.red = red
        self.green = green
        self.blue = blue
        self.opacity = opacity
    }

    public var color: Color {
        Color(
            .sRGB,
            red: Double(red) / 255,
            green: Double(green) / 255,
            blue: Double(blue) / 255,
            opacity: opacity
        )
    }
}

public enum Dev3SemanticColor: String, CaseIterable, Sendable {
    case surfaceBase
    case surfaceRaised
    case surfaceRaisedHover
    case surfaceElevated
    case surfaceElevatedHover
    case surfaceOverlay
    case textPrimary
    case textSecondary
    case textTertiary
    case textMuted
    case borderDefault
    case borderActive
    case accent
    case accentHover
    case danger
    case success
    case successHover
    case warning
    case favorite
    case awake
    case awakeHover
    case diffSearchHighlightFrom
    case diffSearchHighlightTo
    case chart1
    case chart2
    case chart3
    case chart4
    case chart5
    case chart6
    case statGold
    case statFire
    case hintBackground
    case hintForeground
    case hintBorder
    case hintTyped
    case backgroundGradientStart
    case backgroundGradientMiddle
    case backgroundGradientEnd
    case glassColumn
    case glassCard
    case glassCardHover
    case glassHeader
    case glassBorderColumn
    case glassBorderCard
    case glassBorderCardHover
}

public enum Dev3StatusToken: String, CaseIterable, Sendable {
    case todo
    case inProgress = "in-progress"
    case userQuestions = "user-questions"
    case reviewByAi = "review-by-ai"
    case reviewByUser = "review-by-user"
    case reviewByColleague = "review-by-colleague"
    case completed
    case cancelled
}

public struct Dev3ThemeMetrics: Sendable {
    public let bgGradAngle: Double
    public let glassColumnAlpha: Double
    public let glassCardAlpha: Double
    public let glassCardHoverAlpha: Double
    public let glassHeaderAlpha: Double
    public let glassBlurColumn: Double
    public let glassBlurHeader: Double
    public let glassBorderColumnAlpha: Double
    public let glassBorderCardAlpha: Double
    public let glassBorderCardHoverAlpha: Double
    public let glowStartAlpha: Double
    public let glowMidAlpha: Double
    public let glowLineAlpha: Double
}

public struct Dev3TerminalPalette: Sendable {
    public let backgroundValue: Dev3RGBA
    public let foregroundValue: Dev3RGBA
    public let cursorValue: Dev3RGBA
    public let selectionBackgroundValue: Dev3RGBA
    public let blackValue: Dev3RGBA
    public let redValue: Dev3RGBA
    public let greenValue: Dev3RGBA
    public let yellowValue: Dev3RGBA
    public let blueValue: Dev3RGBA
    public let magentaValue: Dev3RGBA
    public let cyanValue: Dev3RGBA
    public let whiteValue: Dev3RGBA
    public let brightBlackValue: Dev3RGBA
    public let brightRedValue: Dev3RGBA
    public let brightGreenValue: Dev3RGBA
    public let brightYellowValue: Dev3RGBA
    public let brightBlueValue: Dev3RGBA
    public let brightMagentaValue: Dev3RGBA
    public let brightCyanValue: Dev3RGBA
    public let brightWhiteValue: Dev3RGBA

    public var background: Color {
        backgroundValue.color
    }

    public var foreground: Color {
        foregroundValue.color
    }

    public var cursor: Color {
        cursorValue.color
    }

    public var selectionBackground: Color {
        selectionBackgroundValue.color
    }

    public var black: Color {
        blackValue.color
    }

    public var red: Color {
        redValue.color
    }

    public var green: Color {
        greenValue.color
    }

    public var yellow: Color {
        yellowValue.color
    }

    public var blue: Color {
        blueValue.color
    }

    public var magenta: Color {
        magentaValue.color
    }

    public var cyan: Color {
        cyanValue.color
    }

    public var white: Color {
        whiteValue.color
    }

    public var brightBlack: Color {
        brightBlackValue.color
    }

    public var brightRed: Color {
        brightRedValue.color
    }

    public var brightGreen: Color {
        brightGreenValue.color
    }

    public var brightYellow: Color {
        brightYellowValue.color
    }

    public var brightBlue: Color {
        brightBlueValue.color
    }

    public var brightMagenta: Color {
        brightMagentaValue.color
    }

    public var brightCyan: Color {
        brightCyanValue.color
    }

    public var brightWhite: Color {
        brightWhiteValue.color
    }
}

public struct Dev3ThemePalette: Sendable {
    private let semanticValues: [Dev3SemanticColor: Dev3RGBA]
    public let metrics: Dev3ThemeMetrics
    private let statusValues: [Dev3StatusToken: Dev3RGBA]
    public let labelValues: [Dev3RGBA]
    public let terminal: Dev3TerminalPalette

    fileprivate init(
        semanticValues: [Dev3SemanticColor: Dev3RGBA],
        metrics: Dev3ThemeMetrics,
        statusValues: [Dev3StatusToken: Dev3RGBA],
        labelValues: [Dev3RGBA],
        terminal: Dev3TerminalPalette
    ) {
        self.semanticValues = semanticValues
        self.metrics = metrics
        self.statusValues = statusValues
        self.labelValues = labelValues
        self.terminal = terminal
    }

    public func value(_ token: Dev3SemanticColor) -> Dev3RGBA {
        guard let value = semanticValues[token] else {
            preconditionFailure("Missing generated color token: \(token.rawValue)")
        }
        return value
    }

    public func color(_ token: Dev3SemanticColor) -> Color {
        value(token).color
    }

    public func statusValue(_ status: Dev3StatusToken) -> Dev3RGBA {
        guard let value = statusValues[status] else {
            preconditionFailure("Missing generated status color: \(status.rawValue)")
        }
        return value
    }

    public func statusColor(_ status: Dev3StatusToken) -> Color {
        statusValue(status).color
    }

    public func labelColor(at index: Int) -> Color {
        precondition(!labelValues.isEmpty, "Generated label palette is empty")
        let normalizedIndex = ((index % labelValues.count) + labelValues.count) % labelValues.count
        return labelValues[normalizedIndex].color
    }

    public var surfaceBase: Color {
        color(.surfaceBase)
    }

    public var surfaceRaised: Color {
        color(.surfaceRaised)
    }

    public var surfaceRaisedHover: Color {
        color(.surfaceRaisedHover)
    }

    public var surfaceElevated: Color {
        color(.surfaceElevated)
    }

    public var surfaceElevatedHover: Color {
        color(.surfaceElevatedHover)
    }

    public var surfaceOverlay: Color {
        color(.surfaceOverlay)
    }

    public var textPrimary: Color {
        color(.textPrimary)
    }

    public var textSecondary: Color {
        color(.textSecondary)
    }

    public var textTertiary: Color {
        color(.textTertiary)
    }

    public var textMuted: Color {
        color(.textMuted)
    }

    public var borderDefault: Color {
        color(.borderDefault)
    }

    public var borderActive: Color {
        color(.borderActive)
    }

    public var accent: Color {
        color(.accent)
    }

    public var accentHover: Color {
        color(.accentHover)
    }

    public var danger: Color {
        color(.danger)
    }

    public var success: Color {
        color(.success)
    }

    public var successHover: Color {
        color(.successHover)
    }

    public var warning: Color {
        color(.warning)
    }

    public var favorite: Color {
        color(.favorite)
    }

    public var awake: Color {
        color(.awake)
    }

    public var awakeHover: Color {
        color(.awakeHover)
    }

    public var diffSearchHighlightFrom: Color {
        color(.diffSearchHighlightFrom)
    }

    public var diffSearchHighlightTo: Color {
        color(.diffSearchHighlightTo)
    }

    public var chart1: Color {
        color(.chart1)
    }

    public var chart2: Color {
        color(.chart2)
    }

    public var chart3: Color {
        color(.chart3)
    }

    public var chart4: Color {
        color(.chart4)
    }

    public var chart5: Color {
        color(.chart5)
    }

    public var chart6: Color {
        color(.chart6)
    }

    public var statGold: Color {
        color(.statGold)
    }

    public var statFire: Color {
        color(.statFire)
    }

    public var hintBackground: Color {
        color(.hintBackground)
    }

    public var hintForeground: Color {
        color(.hintForeground)
    }

    public var hintBorder: Color {
        color(.hintBorder)
    }

    public var hintTyped: Color {
        color(.hintTyped)
    }

    public var backgroundGradientStart: Color {
        color(.backgroundGradientStart)
    }

    public var backgroundGradientMiddle: Color {
        color(.backgroundGradientMiddle)
    }

    public var backgroundGradientEnd: Color {
        color(.backgroundGradientEnd)
    }

    public var glassColumn: Color {
        color(.glassColumn)
    }

    public var glassCard: Color {
        color(.glassCard)
    }

    public var glassCardHover: Color {
        color(.glassCardHover)
    }

    public var glassHeader: Color {
        color(.glassHeader)
    }

    public var glassBorderColumn: Color {
        color(.glassBorderColumn)
    }

    public var glassBorderCard: Color {
        color(.glassBorderCard)
    }

    public var glassBorderCardHover: Color {
        color(.glassBorderCardHover)
    }
}

public enum Dev3ThemeMode: String, CaseIterable, Sendable {
    case system
    case dark
    case light

    public func palette(systemColorScheme: ColorScheme) -> Dev3ThemePalette {
        switch self {
        case .system:
            Dev3Theme.palette(for: systemColorScheme)
        case .dark:
            Dev3Theme.dark
        case .light:
            Dev3Theme.light
        }
    }
}

public enum Dev3Theme {
    public static let dark = Dev3ThemePalette(
        semanticValues: [
            .surfaceBase: Dev3RGBA(red: 6, green: 9, blue: 21),
            .surfaceRaised: Dev3RGBA(red: 14, green: 18, blue: 30),
            .surfaceRaisedHover: Dev3RGBA(red: 23, green: 28, blue: 44),
            .surfaceElevated: Dev3RGBA(red: 21, green: 26, blue: 41),
            .surfaceElevatedHover: Dev3RGBA(red: 35, green: 40, blue: 58),
            .surfaceOverlay: Dev3RGBA(red: 17, green: 23, blue: 37),
            .textPrimary: Dev3RGBA(red: 250, green: 252, blue: 255),
            .textSecondary: Dev3RGBA(red: 170, green: 187, blue: 212),
            .textTertiary: Dev3RGBA(red: 115, green: 133, blue: 160),
            .textMuted: Dev3RGBA(red: 82, green: 98, blue: 121),
            .borderDefault: Dev3RGBA(red: 32, green: 38, blue: 55),
            .borderActive: Dev3RGBA(red: 52, green: 58, blue: 83),
            .accent: Dev3RGBA(red: 68, green: 150, blue: 255),
            .accentHover: Dev3RGBA(red: 43, green: 114, blue: 255),
            .danger: Dev3RGBA(red: 255, green: 130, blue: 130),
            .success: Dev3RGBA(red: 74, green: 222, blue: 128),
            .successHover: Dev3RGBA(red: 34, green: 197, blue: 94),
            .warning: Dev3RGBA(red: 250, green: 204, blue: 21),
            .favorite: Dev3RGBA(red: 245, green: 197, blue: 66),
            .awake: Dev3RGBA(red: 251, green: 146, blue: 60),
            .awakeHover: Dev3RGBA(red: 249, green: 115, blue: 22),
            .diffSearchHighlightFrom: Dev3RGBA(red: 255, green: 227, blue: 138),
            .diffSearchHighlightTo: Dev3RGBA(red: 255, green: 166, blue: 196),
            .chart1: Dev3RGBA(red: 68, green: 150, blue: 255),
            .chart2: Dev3RGBA(red: 167, green: 139, blue: 250),
            .chart3: Dev3RGBA(red: 74, green: 222, blue: 128),
            .chart4: Dev3RGBA(red: 251, green: 191, blue: 36),
            .chart5: Dev3RGBA(red: 244, green: 114, blue: 182),
            .chart6: Dev3RGBA(red: 45, green: 212, blue: 191),
            .statGold: Dev3RGBA(red: 212, green: 175, blue: 55),
            .statFire: Dev3RGBA(red: 249, green: 115, blue: 22),
            .hintBackground: Dev3RGBA(red: 253, green: 224, blue: 71),
            .hintForeground: Dev3RGBA(red: 28, green: 25, blue: 23),
            .hintBorder: Dev3RGBA(red: 202, green: 138, blue: 4),
            .hintTyped: Dev3RGBA(red: 185, green: 28, blue: 28),
            .backgroundGradientStart: Dev3RGBA(red: 6, green: 9, blue: 21),
            .backgroundGradientMiddle: Dev3RGBA(red: 15, green: 23, blue: 49),
            .backgroundGradientEnd: Dev3RGBA(red: 24, green: 13, blue: 41),
            .glassColumn: Dev3RGBA(red: 12, green: 16, blue: 23, opacity: 0.7),
            .glassCard: Dev3RGBA(red: 255, green: 255, blue: 255, opacity: 0.04),
            .glassCardHover: Dev3RGBA(red: 255, green: 255, blue: 255, opacity: 0.09),
            .glassHeader: Dev3RGBA(red: 12, green: 15, blue: 23, opacity: 0.46),
            .glassBorderColumn: Dev3RGBA(red: 255, green: 255, blue: 255, opacity: 0.06),
            .glassBorderCard: Dev3RGBA(red: 255, green: 255, blue: 255, opacity: 0.09),
            .glassBorderCardHover: Dev3RGBA(red: 255, green: 255, blue: 255, opacity: 0.17)
        ],
        metrics: Dev3ThemeMetrics(
            bgGradAngle: 115,
            glassColumnAlpha: 0.7,
            glassCardAlpha: 0.04,
            glassCardHoverAlpha: 0.09,
            glassHeaderAlpha: 0.46,
            glassBlurColumn: 12,
            glassBlurHeader: 16,
            glassBorderColumnAlpha: 0.06,
            glassBorderCardAlpha: 0.09,
            glassBorderCardHoverAlpha: 0.17,
            glowStartAlpha: 0.17,
            glowMidAlpha: 0.04,
            glowLineAlpha: 0.46
        ),
        statusValues: [
            .todo: Dev3RGBA(red: 112, green: 227, blue: 255),
            .inProgress: Dev3RGBA(red: 175, green: 186, blue: 255),
            .userQuestions: Dev3RGBA(red: 255, green: 163, blue: 83),
            .reviewByAi: Dev3RGBA(red: 160, green: 174, blue: 192),
            .reviewByUser: Dev3RGBA(red: 255, green: 229, blue: 95),
            .reviewByColleague: Dev3RGBA(red: 196, green: 165, blue: 255),
            .completed: Dev3RGBA(red: 60, green: 243, blue: 176),
            .cancelled: Dev3RGBA(red: 255, green: 130, blue: 130)
        ],
        labelValues: [
            Dev3RGBA(red: 239, green: 68, blue: 68),
            Dev3RGBA(red: 20, green: 184, blue: 166),
            Dev3RGBA(red: 249, green: 115, blue: 22),
            Dev3RGBA(red: 139, green: 92, blue: 246),
            Dev3RGBA(red: 132, green: 204, blue: 22),
            Dev3RGBA(red: 236, green: 72, blue: 153),
            Dev3RGBA(red: 6, green: 182, blue: 212),
            Dev3RGBA(red: 234, green: 179, blue: 8),
            Dev3RGBA(red: 59, green: 130, blue: 246),
            Dev3RGBA(red: 34, green: 197, blue: 94),
            Dev3RGBA(red: 244, green: 63, blue: 94),
            Dev3RGBA(red: 99, green: 102, blue: 241)
        ],
        terminal: Dev3TerminalPalette(
            backgroundValue: Dev3RGBA(red: 26, green: 27, blue: 38),
            foregroundValue: Dev3RGBA(red: 169, green: 177, blue: 214),
            cursorValue: Dev3RGBA(red: 192, green: 202, blue: 245),
            selectionBackgroundValue: Dev3RGBA(red: 51, green: 70, blue: 124),
            blackValue: Dev3RGBA(red: 21, green: 22, blue: 30),
            redValue: Dev3RGBA(red: 247, green: 118, blue: 142),
            greenValue: Dev3RGBA(red: 158, green: 206, blue: 106),
            yellowValue: Dev3RGBA(red: 224, green: 175, blue: 104),
            blueValue: Dev3RGBA(red: 122, green: 162, blue: 247),
            magentaValue: Dev3RGBA(red: 187, green: 154, blue: 247),
            cyanValue: Dev3RGBA(red: 125, green: 207, blue: 255),
            whiteValue: Dev3RGBA(red: 169, green: 177, blue: 214),
            brightBlackValue: Dev3RGBA(red: 65, green: 72, blue: 104),
            brightRedValue: Dev3RGBA(red: 247, green: 118, blue: 142),
            brightGreenValue: Dev3RGBA(red: 158, green: 206, blue: 106),
            brightYellowValue: Dev3RGBA(red: 224, green: 175, blue: 104),
            brightBlueValue: Dev3RGBA(red: 122, green: 162, blue: 247),
            brightMagentaValue: Dev3RGBA(red: 187, green: 154, blue: 247),
            brightCyanValue: Dev3RGBA(red: 125, green: 207, blue: 255),
            brightWhiteValue: Dev3RGBA(red: 192, green: 202, blue: 245)
        )
    )

    public static let light = Dev3ThemePalette(
        semanticValues: [
            .surfaceBase: Dev3RGBA(red: 240, green: 242, blue: 250),
            .surfaceRaised: Dev3RGBA(red: 255, green: 255, blue: 255),
            .surfaceRaisedHover: Dev3RGBA(red: 240, green: 241, blue: 248),
            .surfaceElevated: Dev3RGBA(red: 237, green: 239, blue: 247),
            .surfaceElevatedHover: Dev3RGBA(red: 226, green: 229, blue: 240),
            .surfaceOverlay: Dev3RGBA(red: 255, green: 255, blue: 255),
            .textPrimary: Dev3RGBA(red: 15, green: 23, blue: 42),
            .textSecondary: Dev3RGBA(red: 71, green: 85, blue: 105),
            .textTertiary: Dev3RGBA(red: 100, green: 116, blue: 139),
            .textMuted: Dev3RGBA(red: 148, green: 163, blue: 184),
            .borderDefault: Dev3RGBA(red: 203, green: 213, blue: 225),
            .borderActive: Dev3RGBA(red: 165, green: 180, blue: 202),
            .accent: Dev3RGBA(red: 59, green: 130, blue: 246),
            .accentHover: Dev3RGBA(red: 37, green: 99, blue: 235),
            .danger: Dev3RGBA(red: 220, green: 38, blue: 38),
            .success: Dev3RGBA(red: 22, green: 163, blue: 74),
            .successHover: Dev3RGBA(red: 21, green: 128, blue: 61),
            .warning: Dev3RGBA(red: 202, green: 138, blue: 4),
            .favorite: Dev3RGBA(red: 202, green: 152, blue: 20),
            .awake: Dev3RGBA(red: 217, green: 119, blue: 6),
            .awakeHover: Dev3RGBA(red: 180, green: 83, blue: 9),
            .diffSearchHighlightFrom: Dev3RGBA(red: 250, green: 204, blue: 21),
            .diffSearchHighlightTo: Dev3RGBA(red: 236, green: 72, blue: 153),
            .chart1: Dev3RGBA(red: 59, green: 130, blue: 246),
            .chart2: Dev3RGBA(red: 139, green: 92, blue: 246),
            .chart3: Dev3RGBA(red: 22, green: 163, blue: 74),
            .chart4: Dev3RGBA(red: 217, green: 119, blue: 6),
            .chart5: Dev3RGBA(red: 219, green: 39, blue: 119),
            .chart6: Dev3RGBA(red: 13, green: 148, blue: 136),
            .statGold: Dev3RGBA(red: 184, green: 134, blue: 11),
            .statFire: Dev3RGBA(red: 234, green: 88, blue: 12),
            .hintBackground: Dev3RGBA(red: 252, green: 211, blue: 77),
            .hintForeground: Dev3RGBA(red: 28, green: 25, blue: 23),
            .hintBorder: Dev3RGBA(red: 180, green: 83, blue: 9),
            .hintTyped: Dev3RGBA(red: 185, green: 28, blue: 28),
            .backgroundGradientStart: Dev3RGBA(red: 218, green: 227, blue: 238),
            .backgroundGradientMiddle: Dev3RGBA(red: 225, green: 229, blue: 212),
            .backgroundGradientEnd: Dev3RGBA(red: 180, green: 181, blue: 196),
            .glassColumn: Dev3RGBA(red: 255, green: 255, blue: 255, opacity: 0.52),
            .glassCard: Dev3RGBA(red: 255, green: 255, blue: 255, opacity: 0.72),
            .glassCardHover: Dev3RGBA(red: 255, green: 255, blue: 255, opacity: 0.88),
            .glassHeader: Dev3RGBA(red: 255, green: 255, blue: 255, opacity: 0.6),
            .glassBorderColumn: Dev3RGBA(red: 0, green: 0, blue: 0, opacity: 0.05),
            .glassBorderCard: Dev3RGBA(red: 0, green: 0, blue: 0, opacity: 0.06),
            .glassBorderCardHover: Dev3RGBA(red: 0, green: 0, blue: 0, opacity: 0.13)
        ],
        metrics: Dev3ThemeMetrics(
            bgGradAngle: 135,
            glassColumnAlpha: 0.52,
            glassCardAlpha: 0.72,
            glassCardHoverAlpha: 0.88,
            glassHeaderAlpha: 0.6,
            glassBlurColumn: 18,
            glassBlurHeader: 22,
            glassBorderColumnAlpha: 0.05,
            glassBorderCardAlpha: 0.06,
            glassBorderCardHoverAlpha: 0.13,
            glowStartAlpha: 0.2,
            glowMidAlpha: 0.06,
            glowLineAlpha: 0.45
        ),
        statusValues: [
            .todo: Dev3RGBA(red: 8, green: 145, blue: 178),
            .inProgress: Dev3RGBA(red: 99, green: 102, blue: 241),
            .userQuestions: Dev3RGBA(red: 234, green: 88, blue: 12),
            .reviewByAi: Dev3RGBA(red: 100, green: 116, blue: 139),
            .reviewByUser: Dev3RGBA(red: 202, green: 138, blue: 4),
            .reviewByColleague: Dev3RGBA(red: 139, green: 92, blue: 246),
            .completed: Dev3RGBA(red: 5, green: 150, blue: 105),
            .cancelled: Dev3RGBA(red: 220, green: 38, blue: 38)
        ],
        labelValues: [
            Dev3RGBA(red: 239, green: 68, blue: 68),
            Dev3RGBA(red: 20, green: 184, blue: 166),
            Dev3RGBA(red: 249, green: 115, blue: 22),
            Dev3RGBA(red: 139, green: 92, blue: 246),
            Dev3RGBA(red: 132, green: 204, blue: 22),
            Dev3RGBA(red: 236, green: 72, blue: 153),
            Dev3RGBA(red: 6, green: 182, blue: 212),
            Dev3RGBA(red: 234, green: 179, blue: 8),
            Dev3RGBA(red: 59, green: 130, blue: 246),
            Dev3RGBA(red: 34, green: 197, blue: 94),
            Dev3RGBA(red: 244, green: 63, blue: 94),
            Dev3RGBA(red: 99, green: 102, blue: 241)
        ],
        terminal: Dev3TerminalPalette(
            backgroundValue: Dev3RGBA(red: 255, green: 255, blue: 255),
            foregroundValue: Dev3RGBA(red: 36, green: 41, blue: 47),
            cursorValue: Dev3RGBA(red: 36, green: 41, blue: 47),
            selectionBackgroundValue: Dev3RGBA(red: 3, green: 102, blue: 214, opacity: 0.145098),
            blackValue: Dev3RGBA(red: 36, green: 41, blue: 46),
            redValue: Dev3RGBA(red: 215, green: 58, blue: 73),
            greenValue: Dev3RGBA(red: 40, green: 167, blue: 69),
            yellowValue: Dev3RGBA(red: 154, green: 103, blue: 0),
            blueValue: Dev3RGBA(red: 0, green: 92, blue: 197),
            magentaValue: Dev3RGBA(red: 90, green: 50, blue: 163),
            cyanValue: Dev3RGBA(red: 5, green: 152, blue: 188),
            whiteValue: Dev3RGBA(red: 87, green: 96, blue: 106),
            brightBlackValue: Dev3RGBA(red: 110, green: 119, blue: 129),
            brightRedValue: Dev3RGBA(red: 203, green: 36, blue: 49),
            brightGreenValue: Dev3RGBA(red: 34, green: 134, blue: 58),
            brightYellowValue: Dev3RGBA(red: 176, green: 136, blue: 0),
            brightBlueValue: Dev3RGBA(red: 3, green: 102, blue: 214),
            brightMagentaValue: Dev3RGBA(red: 111, green: 66, blue: 193),
            brightCyanValue: Dev3RGBA(red: 49, green: 146, blue: 170),
            brightWhiteValue: Dev3RGBA(red: 209, green: 213, blue: 218)
        )
    )

    public static func palette(for colorScheme: ColorScheme) -> Dev3ThemePalette {
        colorScheme == .dark ? dark : light
    }
}

public extension Color {
    static func dev3(_ token: Dev3SemanticColor, scheme: ColorScheme) -> Color {
        Dev3Theme.palette(for: scheme).color(token)
    }

    static func dev3Status(_ status: Dev3StatusToken, scheme: ColorScheme) -> Color {
        Dev3Theme.palette(for: scheme).statusColor(status)
    }
}

public enum Dev3Glyph {
    public static let fontName = "JetBrainsMono Nerd Font Mono"
    public static let terminal = "\u{F120}"
    public static let chevronLeft = "\u{F053}"
    public static let chevronRight = "\u{F054}"
    public static let chevronDown = "\u{F078}"
    public static let check = "\u{F00C}"
    public static let windows = "\u{F05C2}"
    public static let panes = "\u{F0570}"
    public static let fileTree = "\u{F0645}"
    public static let sourceBranch = "\u{F0401}"
    public static let openInNew = "\u{F0379}"
    public static let ethernet = "\u{F0317}"
    public static let memory = "\u{F035B}"
    public static let keyboard = "\u{F030C}"
    public static let bolt = "\u{F0E7}"
}

public enum Dev3ThemeSourceTokens {
    public static let dark: [String: String] = [
        "surface-base": "6 9 21",
        "surface-raised": "14 18 30",
        "surface-raised-hover": "23 28 44",
        "surface-elevated": "21 26 41",
        "surface-elevated-hover": "35 40 58",
        "surface-overlay": "17 23 37",
        "text-primary": "250 252 255",
        "text-secondary": "170 187 212",
        "text-tertiary": "115 133 160",
        "text-muted": "82 98 121",
        "border-default": "32 38 55",
        "border-active": "52 58 83",
        "accent": "68 150 255",
        "accent-hover": "43 114 255",
        "danger": "255 130 130",
        "success": "74 222 128",
        "success-hover": "34 197 94",
        "warning": "250 204 21",
        "favorite": "245 197 66",
        "awake": "251 146 60",
        "awake-hover": "249 115 22",
        "diff-search-highlight-from": "255 227 138",
        "diff-search-highlight-to": "255 166 196",
        "chart-1": "68 150 255",
        "chart-2": "167 139 250",
        "chart-3": "74 222 128",
        "chart-4": "251 191 36",
        "chart-5": "244 114 182",
        "chart-6": "45 212 191",
        "stat-gold": "212 175 55",
        "stat-fire": "249 115 22",
        "hint-bg": "253 224 71",
        "hint-fg": "28 25 23",
        "hint-border": "202 138 4",
        "hint-typed": "185 28 28",
        "bg-grad-angle": "115deg",
        "bg-grad-from": "#060915",
        "bg-grad-mid": "#0f1731",
        "bg-grad-to": "#180d29",
        "glass-column-rgb": "12 16 23",
        "glass-column-alpha": "0.7",
        "glass-card-rgb": "255 255 255",
        "glass-card-alpha": "0.04",
        "glass-card-hover-alpha": "0.09",
        "glass-header-rgb": "12 15 23",
        "glass-header-alpha": "0.46",
        "glass-blur-column": "12px",
        "glass-blur-header": "16px",
        "glass-border-rgb": "255 255 255",
        "glass-border-column-alpha": "0.06",
        "glass-border-card-alpha": "0.09",
        "glass-border-card-hover-alpha": "0.17",
        "glow-start-alpha": "0.17",
        "glow-mid-alpha": "0.04",
        "glow-line-alpha": "0.46",
        "shadow-column": "0 10px 30px -10px rgb(0 0 0 / 0.3)",
        "shadow-card-hover": "0 8px 20px -6px rgb(0 0 0 / 0.25)"
    ]

    public static let light: [String: String] = [
        "surface-base": "240 242 250",
        "surface-raised": "255 255 255",
        "surface-raised-hover": "240 241 248",
        "surface-elevated": "237 239 247",
        "surface-elevated-hover": "226 229 240",
        "surface-overlay": "255 255 255",
        "text-primary": "15 23 42",
        "text-secondary": "71 85 105",
        "text-tertiary": "100 116 139",
        "text-muted": "148 163 184",
        "border-default": "203 213 225",
        "border-active": "165 180 202",
        "accent": "59 130 246",
        "accent-hover": "37 99 235",
        "danger": "220 38 38",
        "success": "22 163 74",
        "success-hover": "21 128 61",
        "warning": "202 138 4",
        "favorite": "202 152 20",
        "awake": "217 119 6",
        "awake-hover": "180 83 9",
        "diff-search-highlight-from": "250 204 21",
        "diff-search-highlight-to": "236 72 153",
        "chart-1": "59 130 246",
        "chart-2": "139 92 246",
        "chart-3": "22 163 74",
        "chart-4": "217 119 6",
        "chart-5": "219 39 119",
        "chart-6": "13 148 136",
        "stat-gold": "184 134 11",
        "stat-fire": "234 88 12",
        "hint-bg": "252 211 77",
        "hint-fg": "28 25 23",
        "hint-border": "180 83 9",
        "hint-typed": "185 28 28",
        "bg-grad-angle": "135deg",
        "bg-grad-from": "#dae3ee",
        "bg-grad-mid": "#e1e5d4",
        "bg-grad-to": "#b4b5c4",
        "glass-column-rgb": "255 255 255",
        "glass-column-alpha": "0.52",
        "glass-card-rgb": "255 255 255",
        "glass-card-alpha": "0.72",
        "glass-card-hover-alpha": "0.88",
        "glass-header-rgb": "255 255 255",
        "glass-header-alpha": "0.6",
        "glass-blur-column": "18px",
        "glass-blur-header": "22px",
        "glass-border-rgb": "0 0 0",
        "glass-border-column-alpha": "0.05",
        "glass-border-card-alpha": "0.06",
        "glass-border-card-hover-alpha": "0.13",
        "glow-start-alpha": "0.20",
        "glow-mid-alpha": "0.06",
        "glow-line-alpha": "0.45",
        "shadow-column": "0 8px 30px -8px rgb(80 100 140 / 0.13), 0 2px 8px -2px rgb(80 100 140 / 0.06)",
        "shadow-card-hover": "0 8px 24px -6px rgb(80 100 140 / 0.14)"
    ]
}

// swiftlint:enable file_length
