// Catppuccin tmux theme palettes — inlined as string constants so they
// survive bun bundling without needing fs reads at runtime.
// Source files kept in src/bun/tmux-themes/ for reference.

export const CATPPUCCIN_MOCHA = `# --> Catppuccin (Mocha)
set -ogq @thm_bg "#1e1e2e"
set -ogq @thm_fg "#cdd6f4"
set -ogq @thm_rosewater "#f5e0dc"
set -ogq @thm_flamingo "#f2cdcd"
set -ogq @thm_pink "#f5c2e7"
set -ogq @thm_mauve "#cba6f7"
set -ogq @thm_red "#f38ba8"
set -ogq @thm_maroon "#eba0ac"
set -ogq @thm_peach "#fab387"
set -ogq @thm_yellow "#f9e2af"
set -ogq @thm_green "#a6e3a1"
set -ogq @thm_teal "#94e2d5"
set -ogq @thm_sky "#89dceb"
set -ogq @thm_sapphire "#74c7ec"
set -ogq @thm_blue "#89b4fa"
set -ogq @thm_lavender "#b4befe"
set -ogq @thm_subtext_1 "#a6adc8"
set -ogq @thm_subtext_0 "#bac2de"
set -ogq @thm_overlay_2 "#9399b2"
set -ogq @thm_overlay_1 "#7f849c"
set -ogq @thm_overlay_0 "#6c7086"
set -ogq @thm_surface_2 "#585b70"
set -ogq @thm_surface_1 "#45475a"
set -ogq @thm_surface_0 "#313244"
set -ogq @thm_mantle "#181825"
set -ogq @thm_crust "#11111b"
`;

export const CATPPUCCIN_LATTE = `# --> Catppuccin (Latte)
set -ogq @thm_bg "#eff1f5"
set -ogq @thm_fg "#4c4f69"
set -ogq @thm_rosewater "#dc8a78"
set -ogq @thm_flamingo "#dd7878"
set -ogq @thm_pink "#ea76cb"
set -ogq @thm_mauve "#8839ef"
set -ogq @thm_red "#d20f39"
set -ogq @thm_maroon "#e64553"
set -ogq @thm_peach "#fe640b"
set -ogq @thm_yellow "#df8e1d"
set -ogq @thm_green "#40a02b"
set -ogq @thm_teal "#179299"
set -ogq @thm_sky "#04a5e5"
set -ogq @thm_sapphire "#209fb5"
set -ogq @thm_blue "#1e66f5"
set -ogq @thm_lavender "#7287fd"
set -ogq @thm_subtext_1 "#6c6f85"
set -ogq @thm_subtext_0 "#5c5f77"
set -ogq @thm_overlay_2 "#7c7f93"
set -ogq @thm_overlay_1 "#8c8fa1"
set -ogq @thm_overlay_0 "#9ca0b0"
set -ogq @thm_surface_2 "#acb0be"
set -ogq @thm_surface_1 "#bcc0cc"
set -ogq @thm_surface_0 "#ccd0da"
set -ogq @thm_mantle "#e6e9ef"
set -ogq @thm_crust "#dce0e8"
`;
