/**
 * Generates src/shared/build-info.generated.ts with the current timestamp
 * baked in as a constant. Run before every build so the app title shows
 * the actual build time, not the startup time.
 */

const getISOWeek = (d: Date): number => {
	const date = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
	date.setUTCDate(date.getUTCDate() + 4 - (date.getUTCDay() || 7));
	const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
	return Math.ceil(((date.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
};

const formatDateTime = (d: Date) => {
	const date = d.toLocaleDateString("en-GB", {
		weekday: "short",
		day: "numeric",
		month: "short",
		year: "numeric",
	});
	const time = d.toLocaleTimeString("en-GB", {
		hour: "2-digit",
		minute: "2-digit",
		second: "2-digit",
	});
	return `${date} · W${String(getISOWeek(d)).padStart(2, "0")} · ${time}`;
};

const buildTime = formatDateTime(new Date());
const outPath = `${import.meta.dir}/../src/shared/build-info.generated.ts`;

// Get git short hash
let buildCommit = "unknown";
try {
	const proc = Bun.spawnSync(["git", "rev-parse", "--short=8", "HEAD"]);
	const out = proc.stdout.toString().trim();
	if (out) buildCommit = out;
} catch { /* non-git env */ }

// Get version from package.json
let buildVersion = "0.0.0";
try {
	const pkg = await Bun.file(`${import.meta.dir}/../package.json`).json();
	buildVersion = pkg.version ?? "0.0.0";
} catch { /* */ }

const content = `// Auto-generated by scripts/generate-build-info.ts — do not edit
export const BUILD_TIME = ${JSON.stringify(buildTime)};
export const BUILD_COMMIT = ${JSON.stringify(buildCommit)};
export const BUILD_VERSION = ${JSON.stringify(buildVersion)};
`;

await Bun.write(outPath, content);
console.log(`[build-info] v${buildVersion} ${buildCommit} ${buildTime} → src/shared/build-info.generated.ts`);
