/**
 * Generates src/shared/changelog.generated.ts with all changelog entries
 * baked in as a typed array. Run before every build so production builds
 * have access to changelog data (the change-logs/ directory is not bundled).
 */

import { join } from "path";
import { readdirSync, existsSync } from "fs";
import type { ChangelogEntry } from "../src/shared/types";

const changeLogsDir = join(import.meta.dir, "..", "change-logs");

const entries: ChangelogEntry[] = [];

if (existsSync(changeLogsDir)) {
	for (const year of readdirSync(changeLogsDir)) {
		const yearPath = join(changeLogsDir, year);
		if (!/^\d{4}$/.test(year)) continue;
		for (const month of readdirSync(yearPath)) {
			const monthPath = join(yearPath, month);
			if (!/^\d{2}$/.test(month)) continue;
			for (const day of readdirSync(monthPath)) {
				const dayPath = join(monthPath, day);
				if (!/^\d{2}$/.test(day)) continue;
				for (const file of readdirSync(dayPath)) {
					if (!file.endsWith(".md") || file === "README.md") continue;
					const basename = file.replace(/\.md$/, "");
					const dashIdx = basename.indexOf("-");
					if (dashIdx === -1) continue;
					const type = basename.slice(0, dashIdx);
					const slug = basename.slice(dashIdx + 1);

					const content = await Bun.file(join(dayPath, file)).text();
					const firstSentence =
						content.split(/\.(?:\s|$)/)[0]?.trim() ?? slug;
					const title =
						firstSentence.length > 120
							? firstSentence.slice(0, 117) + "..."
							: firstSentence;

					entries.push({
						date: `${year}-${month}-${day}`,
						type,
						slug,
						title: title || slug,
					});
				}
			}
		}
	}
}

entries.sort((a, b) => b.date.localeCompare(a.date));

const outPath = join(
	import.meta.dir,
	"..",
	"src",
	"shared",
	"changelog.generated.ts",
);

const lines = entries.map((e) => `\t${JSON.stringify(e)},`).join("\n");

const content = `// Auto-generated by scripts/generate-changelog.ts — do not edit
import type { ChangelogEntry } from "./types";

export const CHANGELOG_ENTRIES: ChangelogEntry[] = [
${lines}
];
`;

await Bun.write(outPath, content);
console.log(
	`[changelog] ${entries.length} entries → src/shared/changelog.generated.ts`,
);
