/**
 * Generates src/bun/sound-bundled.ts with base64-encoded task sounds.
 * Electrobun production bundles app resources into a tar archive, so direct
 * filesystem paths to copied assets are not reliable at runtime.
 */

import { join } from "path";
import { readdirSync } from "fs";

const soundsDir = join(import.meta.dir, "..", "src", "assets", "sounds");
const outPath = join(import.meta.dir, "..", "src", "bun", "sound-bundled.ts");

const sounds: Record<string, string> = {};
for (const name of readdirSync(soundsDir).filter((entry) => entry.endsWith(".mp3")).sort()) {
	const bytes = await Bun.file(join(soundsDir, name)).arrayBuffer();
	sounds[name] = Buffer.from(bytes).toString("base64");
}

const content = `// Auto-generated by scripts/generate-sound-bundled.ts — do not edit manually.
// This file is overwritten at build time with real sound data.
export const BUNDLED_SOUNDS: Record<string, string> = ${JSON.stringify(sounds, null, "\t")};
`;

await Bun.write(outPath, content);
console.log(`[sounds] ${Object.keys(sounds).length} sound(s) → src/bun/sound-bundled.ts`);
