/**
 * Generates src/shared/build-info.generated.ts with the current timestamp
 * baked in as a constant. Run before every build so the app title shows
 * the actual build time, not the startup time.
 */

const getISOWeek = (d: Date): number => {
	const date = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
	date.setUTCDate(date.getUTCDate() + 4 - (date.getUTCDay() || 7));
	const yearStart = new Date(Date.UTC(date.getUTCFullYear(), 0, 1));
	return Math.ceil(((date.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
};

const formatDateTime = (d: Date) => {
	const date = d.toLocaleDateString("en-GB", {
		weekday: "short",
		day: "numeric",
		month: "short",
		year: "numeric",
	});
	const time = d.toLocaleTimeString("en-GB", {
		hour: "2-digit",
		minute: "2-digit",
		second: "2-digit",
	});
	return `${date} · W${String(getISOWeek(d)).padStart(2, "0")} · ${time}`;
};

const buildTime = formatDateTime(new Date());
const outPath = `${import.meta.dir}/../src/shared/build-info.generated.ts`;

// Get git short hash
let buildCommit = "unknown";
try {
	const proc = Bun.spawnSync(["git", "rev-parse", "--short=8", "HEAD"]);
	const out = proc.stdout.toString().trim();
	if (out) buildCommit = out;
} catch { /* non-git env */ }

// Commit count on the current branch. Monotonic on `main` because it is
// squash-merged (linear history, +1 per merge) — that property, not git itself, is
// what makes it usable as the canary channel's ordering key. See
// src/shared/update-channel.ts.
let buildOrder = 0;
try {
	const proc = Bun.spawnSync(["git", "rev-list", "--count", "HEAD"]);
	const out = proc.stdout.toString().trim();
	if (out) buildOrder = Number(out) || 0;
} catch { /* non-git env */ }

// The dev3 task this build came out of, "1716" or "1716-1", empty everywhere else.
// Several agents build from their own worktrees against one analytics property, so
// without it every one of their dev builds is the same anonymous "dev" row.
// Read-only: resolves the worktree path against the board's own tasks.json.
let buildTaskLabel = "";
try {
	const marker = "/.dev3.0/worktrees/";
	const cwd = process.cwd();
	const at = cwd.indexOf(marker);
	if (at !== -1) {
		const [slug, taskIdPrefix] = cwd.slice(at + marker.length).split("/");
		const home = process.env.HOME ?? "";
		const tasks = await Bun.file(`${home}/.dev3.0/data/${slug}/tasks.json`).json();
		const task = tasks.find((t: { id: string }) => t.id.startsWith(taskIdPrefix));
		if (task?.seq != null) {
			buildTaskLabel = task.variantIndex != null ? `${task.seq}-${task.variantIndex}` : `${task.seq}`;
		}
	}
} catch { /* not in a dev3 worktree, or the board is unreadable — stay empty */ }

// Get version from package.json
let buildVersion = "0.0.0";
try {
	const pkg = await Bun.file(`${import.meta.dir}/../package.json`).json();
	buildVersion = pkg.version ?? "0.0.0";
} catch { /* */ }

const content = `// Auto-generated by scripts/generate-build-info.ts — do not edit
export const BUILD_TIME = ${JSON.stringify(buildTime)};
export const BUILD_COMMIT = ${JSON.stringify(buildCommit)};
export const BUILD_VERSION = ${JSON.stringify(buildVersion)};
export const BUILD_ORDER = ${JSON.stringify(buildOrder)};
export const BUILD_TASK_LABEL = ${JSON.stringify(buildTaskLabel)};
`;

await Bun.write(outPath, content);
const taskNote = buildTaskLabel ? ` task ${buildTaskLabel}` : "";
console.log(`[build-info] v${buildVersion} ${buildCommit} #${buildOrder}${taskNote} ${buildTime} → src/shared/build-info.generated.ts`);
