/**
 * Pure transform behind `scripts/generate-low-battery.ts`: a file tree pulled from
 * `h0x91b/toolbelt-for-agents` in, one TypeScript module out. Kept apart from the
 * script so the escaping and completeness rules are unit-testable without a clone.
 *
 * Every value is emitted through `JSON.stringify`, never a template literal — the
 * rules are ~100 KB of markdown full of backticks and `${...}`, and hand-escaping
 * that is exactly the job a generator exists to take away.
 */

export interface LowBatterySource {
	/** Upstream commit the tree was read at — baked in so a release can name it. */
	revision: string;
	/** `plugins/low-battery/output-styles/low-battery.md`, verbatim. */
	outputStyle: string;
	/** Paths relative to `plugins/low-battery/skills/low-battery/` → file contents. */
	skillFiles: Record<string, string>;
}

/** Files the skill is useless without — a partial clone must fail, not ship. */
const REQUIRED_SKILL_FILES = ["SKILL.md", "agents/openai.yaml"];

/**
 * Floors, not a catalogue. The templates and reference pages are upstream's to add
 * and rename, so pinning their exact names would turn every upstream edit into a
 * dev3 build failure. These numbers only have to be high enough that a truncated or
 * half-written clone cannot pass.
 */
const MIN_TEMPLATES = 5;
const MIN_REFERENCE = 3;

export class LowBatterySourceError extends Error {}

function countUnder(files: Record<string, string>, prefix: string): number {
	return Object.entries(files).filter(([path, body]) => path.startsWith(prefix) && body.trim()).length;
}

/** Throw unless the tree carries everything dev3 installs. Exported for the tests
 *  that drive the empty/partial-tree cases. */
export function assertCompleteSource(src: LowBatterySource): void {
	if (!src.revision.trim()) throw new LowBatterySourceError("upstream revision is empty");
	if (!src.outputStyle.trim()) throw new LowBatterySourceError("output-styles/low-battery.md is empty or missing");

	const missing = REQUIRED_SKILL_FILES.filter((file) => !src.skillFiles[file]?.trim());
	if (missing.length > 0) {
		throw new LowBatterySourceError(`incomplete low-battery tree — missing: ${missing.join(", ")}`);
	}

	const templates = countUnder(src.skillFiles, "templates/");
	if (templates < MIN_TEMPLATES) {
		throw new LowBatterySourceError(`incomplete low-battery tree — ${templates} templates, expected at least ${MIN_TEMPLATES}`);
	}
	const reference = countUnder(src.skillFiles, "reference/");
	if (reference < MIN_REFERENCE) {
		throw new LowBatterySourceError(`incomplete low-battery tree — ${reference} reference files, expected at least ${MIN_REFERENCE}`);
	}
}

export function generateLowBatteryModule(src: LowBatterySource): string {
	assertCompleteSource(src);

	const entries = Object.keys(src.skillFiles)
		.sort()
		.map((path) => `\t${JSON.stringify(path)}: ${JSON.stringify(src.skillFiles[path])},`)
		.join("\n");

	return `// GENERATED by scripts/generate-low-battery.ts — do not edit by hand.
// Source of truth: https://github.com/h0x91b/toolbelt-for-agents (plugins/low-battery).
// Regenerate with: bun scripts/generate-low-battery.ts

/** Upstream commit this build's rules were pulled from. Surfaced in Global Settings
 *  and \`dev3 doctor\` so "the agent answered differently last version" is answerable. */
export const LOW_BATTERY_REVISION = ${JSON.stringify(src.revision)};

/** The Claude Code output style, frontmatter included. */
export const LOW_BATTERY_OUTPUT_STYLE = ${JSON.stringify(src.outputStyle)};

/** Skill tree, keyed by path relative to the skill directory. */
export const LOW_BATTERY_SKILL_FILES: Record<string, string> = {
${entries}
};
`;
}
